### ISSUE TITLE
Avoid need for `data` in user-interaction with fields through dispatch on `Colon` indices

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#458] opened 2019-10-10 14:49 UTC
We might be able to avoid the need for users to call the function `data` by dispatching on `Colon`:

```julia
xindex(f, i) = i
xindex(f, ::Colon) = 1:f.grid.Nx

yindex(f, i) = i
yindex(f, ::Colon) = 1:f.grid.Ny

zindex(f, i) = i
zindex(f, ::Colon) = 1:f.grid.Nz

@inline getindex(f::Field, i, j, k) = getindex(f.data, xindex(f, i), yindex(f, j), zindex(f, k))
```

Then things like

```julia
imshow(model.velocities.u[:, 1, :])
```

Will plot only the interior points of `u`, avoiding the need to write `imshow(data(model.velocities.u)[:, 1, :])`.

Perhaps this is desirable? Or too surprising that indexing into a field is different from indexing into its `data`? I'm not sure how much we want users to be explicitly aware / interactive with halo regions.

Note that in the future, we may also want to borrow the `Colon` type to mean "all interior points" for specifying things like slices --- or, come up with a different meaningful shorthand.

**Comment by ali-ramadhan** [comment] 2019-10-13 13:28
I like the idea of dispatching on `::Colon` to only return the interior points! I'm not sure how often users would like the halo regions to be part of the output (I suspect more often than not, they'd just want the interior points) but I kind of imagined something like `data(model.velocities.u; halos=true)` for that, although this is kind of cumbersome.

**Comment by glwagner** [comment] 2019-10-15 14:42
What we could move towards is to use either `interior(u)` for all interior points or `u[1, :, :]` for slices; to get all data including halos we would use `data(u)` and `data(u)[1, :, :]` for slices with halos.

**Comment by glwagner** [comment] 2019-10-15 14:44
In some ways, I think the semantics that `data` returns `u.data` might be surprising anyways. So perhaps our current semantics is suboptimal in this respect.

**Comment by ali-ramadhan** [comment] 2021-03-17 02:02
@glwagner I'm gonna close this since I think the issue is irrelevant now that we use `interior(::Field)` so users don't have to interact with `field.data` anymore.

Please reopen if it's still relevant!

**Closed by ali-ramadhan** 2021-03-17 02:02 UTC
Labels: abstractions 🎨, feature 🌟
