### ISSUE TITLE
test Oceananigans returns CUDA error depsite being able to run examples on CPU and GPU

### ISSUE THREAD

**Issue by raphaelouillon** [CliMA/Oceananigans.jl#788] opened 2020-07-02 21:06 UTC
Hi,
I encounter an error when running `pkg> test Oceananigans` despite being able to run example simulation internal_wave.jl on both CPU and GPU. The description of CUDA error code 201 is also attached below

```
ERROR: LoadError: CUDA error (code 201, CUDA_ERROR_INVALID_CONTEXT)
Stacktrace:
 [1] throw_api_error(::CUDAdrv.cudaError_enum) at /home/raphael/.julia/packages/CUDAdrv/Uc14X/src/error.jl:105
 [2] macro expansion at /home/raphael/.julia/packages/CUDAdrv/Uc14X/src/error.jl:112 [inlined]
 [3] cuCtxGetDevice(::Base.RefValue{Int32}) at /home/raphael/.julia/packages/CUDAapi/XuSHC/src/call.jl:93
 [4] device at /home/raphael/.julia/packages/CUDAdrv/Uc14X/src/context.jl:142 [inlined]
 [5] device! at /home/raphael/.julia/packages/CUDAnative/ierw8/src/init.jl:198 [inlined]
 [6] device!(::CUDAdrv.CuDevice) at /home/raphael/.julia/packages/CUDAnative/ierw8/src/init.jl:188
 [7] top-level scope at /home/raphael/.julia/packages/Oceananigans/1xP6n/test/runtests.jl:74
 [8] include(::String) at ./client.jl:439
 [9] top-level scope at none:6
in expression starting at /home/raphael/.julia/packages/Oceananigans/1xP6n/test/runtests.jl:61
ERROR: Package Oceananigans errored during testing
```

Has anyone encountered this issue? I am on master 0.30.0. Thanks for your help!
![Screenshot_2020-07-02 CUDA Driver API CUDA Toolkit Documentation](https://user-images.githubusercontent.com/31293515/86409162-4f484f80-bc86-11ea-8736-bad7a9da5345.png)

**Comment by glwagner** [comment] 2020-07-03 02:20
@raphaelouillon if you are on master, can you try downgrading to v0.30.0 and seeing if the error persists?

@sandreza @ali-ramadhan was this one of the errors that was reported on Oceananigans master?

**Comment by mhudecheck** [comment] 2020-07-03 14:03
@glwagner I'm running into the same issue as well (v0.30.0):

ERROR: LoadError: AssertionError: CUDAdrv.jl did not successfully initialize, and is not usable.
Stacktrace:
 [1] libcuda at /home/mike/.julia/packages/CUDAdrv/Uc14X/src/CUDAdrv.jl:82 [inlined]
 [2] (::CUDAdrv.var"#535#cache_fptr!#11")() at /home/mike/.julia/packages/CUDAapi/XuSHC/src/call.jl:31
 [3] macro expansion at /home/mike/.julia/packages/CUDAapi/XuSHC/src/call.jl:39 [inlined]
 [4] macro expansion at /home/mike/.julia/packages/CUDAdrv/Uc14X/src/libcuda.jl:36 [inlined]
 [5] macro expansion at /home/mike/.julia/packages/CUDAdrv/Uc14X/src/error.jl:110 [inlined]
 [6] cuDeviceGetCount at /home/mike/.julia/packages/CUDAapi/XuSHC/src/call.jl:93 [inlined]
 [7] length at /home/mike/.julia/packages/CUDAdrv/Uc14X/src/devices.jl:105 [inlined]
 [8] iterate(::CUDAdrv.DeviceSet, ::Int64) at /home/mike/.julia/packages/CUDAdrv/Uc14X/src/devices.jl:100 (repeats 2 times)
 [9] iterate at ./iterators.jl:139 [inlined]
 [10] iterate(::Base.Iterators.Enumerate{CUDAdrv.DeviceSet}) at ./iterators.jl:138
 [11] top-level scope at /home/mike/.julia/packages/Oceananigans/1xP6n/src/Oceananigans.jl:131
 [12] include(::Module, ::String) at ./Base.jl:377
 [13] top-level scope at none:2
 [14] eval at ./boot.jl:331 [inlined]
 [15] eval(::Expr) at ./client.jl:449
 [16] top-level scope at ./none:3
in expression starting at /home/mike/.julia/packages/Oceananigans/1xP6n/src/Oceananigans.jl:124

**Comment by glwagner** [comment] 2020-07-07 13:21
@mhudecheck whence does this error arise?

**Comment by glwagner** [comment] 2020-07-07 13:41
@raphaelouillon I can reproduce `ERROR: LoadError: CUDA error (code 201, CUDA_ERROR_INVALID_CONTEXT)` when running `pkg> test Oceananigans` for `0.28.0`--`0.30.0`. Tests run for `0.27.1`, however.

**Comment by glwagner** [comment] 2020-07-07 13:45
@mhudecheck I think that your error has a different provenance. Can you open a separate issue with a few more details about how you triggered it? We'll try to tackle the error @raphaelouillon found on this issue.

**Comment by glwagner** [comment] 2020-07-07 13:47
The error arises in a code block that's intended to pick the GPU with the most memory for the purposing CI testing on GPUs:

https://github.com/CliMA/Oceananigans.jl/blob/v0.30.0/test/runtests.jl#L74

**Comment by raphaelouillon** [comment] 2020-07-07 15:07
Thanks @glwagner. Is there an easy way to skip GPU testing? On my machine, all simulations I tested ran faster on the CPU anyways.

**Comment by glwagner** [comment] 2020-07-07 15:13
@raphaelouillon if you need to run tests for the purpose of development, you can comment out this line:

https://github.com/CliMA/Oceananigans.jl/blob/dd764fe726b2bc5a61136144b4976cd3de498c04/test/runtests.jl#L105

on v0.30.0.

As an aside, on GPUs like the V100 or Titan V, I don't see speed up on GPUs until resolutions of around 64^3 (or larger), I think, with the current version of Oceananigans.

**Comment by ali-ramadhan** [comment] 2020-10-01 17:38
@raphaelouillon @mhudecheck The offending code has been removed in a previous version of Oceananigans.jl so I'm going to close this issue but please reopen if you encounter any more issues.

**Closed by ali-ramadhan** 2020-10-01 17:38 UTC
