### ISSUE TITLE
Making options for NetCDF and JLD2 output writers more unified

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2217] opened 2022-02-03 20:48 UTC
`NetCDFOutputWriter` and `JLD2OutputWriter` currently have different options.

```
  NetCDFOutputWriter(model, outputs; filepath, schedule
                                 array_type = Array{Float32},
                               field_slicer = FieldSlicer(),
                          global_attributes = Dict(),
                          output_attributes = Dict(),
                                 dimensions = Dict(),
                                       mode = nothing,
                                compression = 0,
                                    verbose = false)
```

```
  JLD2OutputWriter(model, outputs; prefix, schedule,
                            dir = ".",
                   field_slicer = FieldSlicer(),
                     array_type = Array{Float32},
                   max_filesize = Inf,
                          force = false,
                           init = noinit,
                      including = [:grid, :coriolis, :buoyancy, :closure],
                        verbose = false,
                           part = 1,
                        jld2_kw = Dict{Symbol, Any}())
```

Some arguments are unique to each writer, but I think it would make things easier and more usable if we unified some of the arguments that really do the same thing. Specifically `filepath` could replace `dir` and `prefix`, and `mode` could replace`force`. I understand that the NetCDF and JLD2 libraries work differently when writing to disk (probably that's where the difference come from) but maybe we can do some translation behind the scenes.

**Comment by glwagner** [comment] 2022-02-03 23:59
I think this might be a duplicate of #884

**Closed** 2022-02-04 00:24 UTC
Labels: duplicate 🧬, user interface/experience 💻

**Comment by tomchor** [comment] 2022-02-04 00:32
Sprry, I wasn't aware that issue existed
