### ISSUE TITLE
benchmarks scripts cannot write CPU to GPU speedup table to html file due to ">" being in filename

### ISSUE THREAD

**Issue by hennyg888** [CliMA/Oceananigans.jl#1672] opened 2021-05-19 15:39 UTC
I tried to run both the shallow water and incompressible benchmarks and ran into problems when they tried to output the CPU to GPU speedup table html file. 
The problem seems to be cause by the html file being named "[model name]_CPU_->_GPU_speedup.html" and ">" not being allowed to be a part of filenames. It was fixed by changing the output filename to "[model name]_CPU_to_GPU_speedup.html".
This issue occurred while running on Windows10, but I think it would likely be a problem elsewhere too where ">" is a reserved character for file and directory names.
@francispoulin

**Comment by glwagner** [comment] 2021-05-19 16:11
Can you provide links to the problematic scripts?

**Comment by ali-ramadhan** [comment] 2021-05-19 16:30
Ah indeed we never encountered this issue since I think we always ran the benchmark scripts on Linux but this could be an issue on Windows.

I think the issue is that the filenames are derived from the title of the tables, e.g. from https://github.com/CliMA/Oceananigans.jl/blob/50ec98e490ce7b30eec4c71dc779865b90eee5fe/benchmark/benchmark_incompressible_model.jl#L39

We could change all instances of `->` to `to`?

**Comment by francispoulin** [comment] 2021-05-19 16:35
One example that reproduced this result was `benchmarks_shallow_water_mode.jl` but incompressible model also had the same issue.

I think that @ali-ramadhan 's suggestion is a simple fix and our current and future windows users will appreciate this.

**Comment by hennyg888** [comment] 2021-05-19 16:48
These are all the lines in the benchmark scripts that I can find where a pretty table and html file is created with a title and filename containing ">".
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_advection_schemes.jl#L39](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_equations_of_state.jl#L41](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_fft_based_poisson_solvers.jl#L41](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl#L41](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_incompressible_model.jl#L39](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_lagrangian_particle_tracking.jl#L49](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_shallow_water_model.jl#L41](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_time_steppers.jl#L39](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_topologies.jl#L39](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_tracers.jl#L64](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_turbulence_closures.jl#L46](url)
[https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_vertically_stretched_incompressible_model.jl#L39](url)

**Comment by ali-ramadhan** [comment] 2021-05-19 16:57
@hennyg888 Nice grepping! If you have some time to open a PR updating those titles/filenames that would be awesome.

**Comment by navidcy** [comment] 2022-11-07 11:29
Is this issue resolved by https://github.com/CliMA/Oceananigans.jl/pull/1678

**Closed** 2023-03-22 16:22 UTC
Labels: bug 🐞
