### ISSUE TITLE
Keeping validation script up-to-date

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1634] opened 2021-05-03 21:30 UTC
This is motivated by the small discussion on the slack channel and my own experiences last week trying to run some of the code there.

Apparently the scripts in the `validation/` directory are not included in CI (probably because they would take too long?), but it would still be nice if they were kept up-to-date with the master branch. @glwagner mentioned the possibility of running occasional CIs specific for validation.

An alternative solution might be creating a different package on github just for the validation scripts. I noticed that JuliaRegistrator creates a new PR every time one of the dependencies is updated. So, by having Oceanigans as a dependency, this process would be made automatic by that and we'd only need to update the PRs if the tests failed.

Thoughts?

**Comment by glwagner** [comment] 2021-05-04 16:00
We've discussed moving `validation` to another repo in the past. Certainly that would decrease our maintenance burden during development, while tracking the Oceananigans version that the validation scripts are "guaranteed" to work with.

The main downside I think is that the validation repo goes stale by design. By putting `validation` in `Oceananigans` and requiring the scripts to run during CI we "enforce" that the scripts are up to date with the API implemented in `master`. This helps the validation scripts better serve their purpose...

One solution might be to split up the scripts in `validation/`. A growing number of the `validation` cases really just use an "eyeball" norm and more serve to demonstrate functionality than to "validate" it in a scientific sense. (This includes the immersed boundary case.) Perhaps we can create a new repo for these cases which achieve most of their value as "advanced examples", while keeping quantitatively valuable validation cases in the main repo.

**Comment by glwagner** [comment] 2021-05-04 19:55
Ah, you mean `CompatHelper`? I think that's true...

**Comment by tomchor** [comment] 2021-05-04 21:39
Yeah, sorry! That's what I meant. I think that would keep the validations up-to-date, and we'd only have to cater to it when we bump the Oceananigans version.

**Comment by glwagner** [comment] 2021-05-05 15:08
I think you're right that alleviates a lot of the issue. We just have to be attentive to the `CompatHelper` PRs.

**Comment by glwagner** [comment] 2023-03-22 16:19
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.

**Closed by glwagner** 2023-03-22 16:19 UTC
