### ISSUE TITLE
Do we really need AbstractCPUArchitecture?

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2072] opened 2021-11-19 20:33 UTC
If we are thinking to unify `MultiCPU` and `MultiGPU` in a more general `MultiArch` which will contain the `child_architecture` information, `AbstractCPUArchitecture` and `AbstractGPUArchitecture` become obsolete...

**Comment by glwagner** [comment] 2021-11-19 20:52
Agree! I think this is a duplicate of #2020 ?

**Comment by simone-silvestri** [comment] 2021-11-19 20:59
Kind of :). I was thinking to just remove the AbstractCPU and AbstractGPU acrhitecture types

**Comment by glwagner** [comment] 2021-11-19 21:07
Ah for sure. Yeah, it doesn't seem like it'd have any impact on the code.

**Comment by simone-silvestri** [comment] 2022-01-20 14:32
No, just `AbstractMultiArchitecture` (which we might want to delete) and `AbstractArchitecture`

**Comment by glwagner** [comment] 2022-01-20 14:42
Then I'm closing

**Closed by glwagner** 2022-01-20 14:42 UTC
Labels: cleanup 🧹
