### ISSUE TITLE
Test that horizontal average is correct over time

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#737] opened 2020-04-25 14:57 UTC
@glwagner suggested that this test could pass at t=0 but fail for t>0 in certain situations (not yet isolated)

We should upgrade this test to include some time dependence.

https://github.com/climate-machine/Oceananigans.jl/blob/22088d335973553b298a67bacebfa80b32e66acf/test/test_diagnostics.jl#L1-L15

**Comment by glwagner** [comment] 2020-07-01 16:40
Closing this since we have not reproduced it.

**Closed by glwagner** 2020-07-01 16:40 UTC
Labels: bug 🐞
