### ISSUE TITLE
Can't use `GradientBoundaryCondition` on the GPU

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2709] opened 2022-08-23 13:05 UTC
Using Julia 1.7.3 and Oceananigans 0.77.1, this code:

```julia
using Oceananigans

grid = RectilinearGrid(GPU(), size=(1, 1, 2), extent=(1, 1, 1))
buoyancy_bottom_bc = GradientBoundaryCondition(1e-5)
buoyancy_bcs = FieldBoundaryConditions(bottom=buoyancy_bottom_bc)
model = NonhydrostaticModel(; grid, tracers=:b, buoyancy=BuoyancyTracer(),
                            boundary_conditions=(; b=buoyancy_bcs))
simulation = Simulation(model; Δt=1, stop_iteration=2)
run!(simulation)
```

produces:

```julia
julia> include("simple_model.jl")
ERROR: LoadError: InvalidIRError: compiling kernel #gpu__fill_bottom_and_top_halo!(KernelAbstractions.CompilerMetadata{KernelAbstractions.NDIteration.StaticSize{(1, 1)}, KernelAbstractions.NDIteration.DynamicCheck, Nothing, Nothing, KernelAbstractions.NDIteration.NDRange{2, KernelAbstractions.NDIteration.StaticSize{(1, 1)}, KernelAbstractions.NDIteration.StaticSize{(1, 1)}, Nothing, Nothing}}, NTuple{4, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}}, Tuple{BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Gradient, Float64}}, Tuple{BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Tuple{Tuple{Face, Center, Center}, Tuple{Center, Face, Center}, Tuple{Center, Center, Face}, Tuple{Center, Center, Center}}, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing}, NamedTuple{(:time, :iteration, :stage), Tuple{Float64, Int64, Int64}}, NamedTuple{(:u, :v, :w, :b), NTuple{4, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}}}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to _fill_bottom_halo!(i, j, grid, c, bc::Union{BoundaryCondition{<:Oceananigans.BoundaryConditions.Value}, BoundaryCondition{<:Oceananigans.BoundaryConditions.Gradient}}, loc, args...) in Oceananigans.BoundaryConditions at /home/greg/.julia/packages/Oceananigans/W63bs/src/BoundaryConditions/fill_halo_regions_value_gradient.jl:73)
```

probably affects `ValueBoundaryCondition` too.

We should probably have regression tests for these boundary conditions, as well.

**Comment by navidcy** [comment] 2022-09-13 02:20
I'm hitting this when I try to run the horizontal convection experiment on GPU....

**Comment by navidcy** [comment] 2022-09-13 02:20
(It's a `ValueBoundaryCondition` for buoyancy at the top in that case...)

**Comment by simone-silvestri** [comment] 2022-09-28 20:18
as for #2530, I also cannot reproduce this error

```
julia> using Oceananigans

julia> grid = RectilinearGrid(GPU(), size=(1, 1, 2), extent=(1, 1, 1))
1×1×2 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on GPU with 3×3×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=1.0
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=0.5

julia> buoyancy_bottom_bc = GradientBoundaryCondition(1e-5)
GradientBoundaryCondition: 1.0e-5

julia> buoyancy_bcs = FieldBoundaryConditions(bottom=buoyancy_bottom_bc)
Oceananigans.FieldBoundaryConditions, with boundary conditions
├── west: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)
├── east: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)
├── south: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)
├── north: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)
├── bottom: GradientBoundaryCondition: 1.0e-5
├── top: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)
└── immersed: DefaultBoundaryCondition (FluxBoundaryCondition: Nothing)

julia> model = NonhydrostaticModel(; grid, tracers=:b, buoyancy=BuoyancyTracer(),
                                   boundary_conditions=(; b=buoyancy_bcs))
NonhydrostaticModel{GPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 1×1×2 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on GPU with 3×3×3 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── tracers: b
├── closure: Nothing
├── buoyancy: BuoyancyTracer with -ĝ = ZDirection
└── coriolis: Nothing

julia> simulation = Simulation(model; Δt=1, stop_iteration=2)
Simulation of NonhydrostaticModel{GPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── Next time step: 1 second
├── Elapsed wall time: 0 seconds
├── Wall time per iteration: NaN years
├── Stop time: Inf years
├── Stop iteration : 2.0
├── Wall time limit: Inf
├── Callbacks: OrderedDict with 4 entries:
│   ├── stop_time_exceeded => Callback of stop_time_exceeded on IterationInterval(1)
│   ├── stop_iteration_exceeded => Callback of stop_iteration_exceeded on IterationInterval(1)
│   ├── wall_time_limit_exceeded => Callback of wall_time_limit_exceeded on IterationInterval(1)
│   └── nan_checker => Callback of NaNChecker for u on IterationInterval(100)
├── Output writers: OrderedDict with no entries
└── Diagnostics: OrderedDict with no entries

julia> run!(simulation)
[ Info: Initializing simulation...
[ Info:     ... simulation initialization complete (4.788 seconds)
[ Info: Executing initial time step...
[ Info:     ... initial time step complete (33.831 seconds).
[ Info: Simulation is stopping. Model iteration 2 has hit or exceeded simulation stop iteration 2.

julia> 

```

**Comment by glwagner** [comment] 2022-09-28 20:24
Is that with Julia 1.8?

**Comment by simone-silvestri** [comment] 2022-09-28 20:25
ah yeah, that maybe is also another clue

**Comment by navidcy** [comment] 2022-11-07 03:55
with Julia 1.8.2 + v0.78.0 the script @glwagner posted at the top runs fine!

shall we close this?

**Comment by navidcy** [comment] 2022-11-07 04:02
with Julia 1.7.3 + Oceananigans v0.78.0 also no problems

**Comment by simone-silvestri** [comment] 2022-11-07 04:48
close close!

**Closed** 2022-11-07 04:55 UTC
Labels: bug 🐞, GPU 👾
