### ISSUE TITLE
GPU architecture and plan_forward_transform

### ISSUE THREAD

**Issue by sam12396** [CliMA/Oceananigans.jl#1317] opened 2021-01-25 15:37 UTC
I am trying to run a case with GPU architecture on my school's HPC but I keep running into this same error (see gpu_error.log). This is my first time using the GPUs on the HPC so I am not sure if this is a user error or a software error. The error comes up during model instantiation.
[gpu_error.log](https://github.com/CliMA/Oceananigans.jl/files/5867606/gpu_error.log)

Let me know if there is anything else you may need. The run script is also attached as a .txt. 
[model_gpu_waves.txt](https://github.com/CliMA/Oceananigans.jl/files/5867635/model_gpu_waves.txt)

**Comment by glwagner** [comment] 2021-01-25 18:29
I think you need to load cuda before you _build_ Oceananigans. You might need to do this from the login node, eg something like

```
module load cuda
julia --project -e 'using Pkg; Pkg.build("Oceananigans")'
```

Is that right @ali-ramadhan ?

The issue is that the functions `plan_forward_transforms` for `CuArray`s are not being loaded:

https://github.com/CliMA/Oceananigans.jl/blob/52bfeb09e3562f639deb32b8807f32a88e3a1cfa/src/Solvers/plan_transforms.jl#L30-L33

Note that your script is a julia file, so you should append it with `.jl` so that it's named `model_gpu_waves.jl`.

As a side comment, you should take care when initializing a model with zero Eulerian flow --- despite that this is common in the literature, it is unlikely to be a physically relevant initial condition (since it excites large inertial oscillations). Some perspective on this issue is provided by [observations reported by Jerry Smith (2006)](https://journals.ametsoc.org/view/journals/phoc/36/7/jpo2910.1.xml?tab_body=abstract-display) and [a preprint that I wrote](https://glwagner.github.io/assets/pdf/near-inertial-waves-turbulence-growth-swell-preprint.pdf)

**Comment by sam12396** [comment] 2021-01-26 13:18
It seems like adding the rebuilding step has fixed that error so thank you!
However, there is another error (see attached error log). Based on my print statements from my run script, the error is occurring when the `run!` command is called or during the run before the first output of progress.
[err_gpu.01.txt](https://github.com/CliMA/Oceananigans.jl/files/5873490/err_gpu.01.txt)
[log_gpu.01.txt](https://github.com/CliMA/Oceananigans.jl/files/5873492/log_gpu.01.txt)

I have run the same case using the CPU architecture and it made it through a couple timesteps so I know that it works. It just runs too slowly on the CPU to be practical to use. 

To your note, I do use .jl extensions but github wouldn't allow me to attach a .jl so I changed it to .txt to post it.

I don't anticipate the zero Eulerian-mean flow to be a huge issue because my forcing starts up very gradually over the first few hours so I would expect that to act as the spin-up you used in your paper. However, you know much more about this than I do. Even with a gradual climb in forcing at the beginning of the run, how would you recommend improving the settings? Can I initialize the Eulerian-mean flow with noise? Or just run a different, more formal spin up case and then initialize from that? 

Thanks so much for your help, this is my first time working with an LES so I am very green.

**Comment by ali-ramadhan** [comment] 2021-01-26 13:47
Sorry about the GPU errors, they're much scarier than they look! Looks like a pretty involved setup so I'll let @glwagner comment on the setup.

In this case it looks like Julia is complaining about an `unsupported dynamic function invocation (call to overdub)` in `Fxn_scale` at line 93

```julia
@inline Fxn_scale(t) = spl_scale(t)
```

which itself is calling some kind of spline

```julia
spl_scale  = Spline1D(secs, df.scale, k=1) 
```

Since these functions are going to be called in GPU kernels, I think everything used by these functions should be made locally available to the functions and any arrays need to be `CuArray`s.

Just looking around your script it looks like `secs` is just a regular array when it should be a `CuArray` if you want to use it in a GPU kernel, e.g. as part of `UniformStokesDrift`.

I think the `df` dataframe object might not be GPU-compatible (i.e. it's not `isbits` and has no Adapt.jl function) so you might not want to use the `df` variable inside GPU kernels. It looks like you mostly use numbers from `df` (?) so you could instead pull out what you need

```julia
const secs = CuArray(...)
const scale = CuArray(...)
const spl_scale  = Spline1D(secs, scale, k=1)
@inline Fxn_scale(t) = spl_scale(t)
```

You might also need to make variables `const`, e.g. `const secs = ...` so that they can be accessed from the GPU kernels.

There's also the question of whether these splines are GPU-compatible, i.e. do they do the right thing on the GPU when given `CuArray`s instead of regular `Array`s. Unfortunately not every Julia package is GPU-compatible and not always efficient if it falls back on CPU methods to deal with `CuArray`s.

I notice you're using Dierckx.jl for splines, which looks like a wrapper around a Fortran library so that's not going to work inside a GPU kernel. The Julia GPU/CUDA compiler can only compile pure Julia code to run on GPUs.

We can look around a bit to see if there's a better package unless Dierckx splines are essential to your setup? Interpolations.jl might be an option but I'm not sure if it's GPU compatible. Worst case scenario maybe it wouldn't be too hard to code up a simple spline/interpolation scheme?

If you're looking for a 5~10x speedup you could try running multithreaded (run `julia -t n` where `n` is the number of threads to use) until a GPU version is up and running.

**Comment by ali-ramadhan** [comment] 2021-01-26 13:50
@sam12396 PS: We also hang out on the #oceananigans channel on Julia Slack, where it might be faster to chat and debug if you're interested. (To join the Julia Slack: https://julialang.org/slack/)

**Comment by ali-ramadhan** [comment] 2021-01-26 15:06
Side note: Might be good to add some tips on writing GPU-compatible forcing functions, boundary conditions, etc. on this page of the documentation: https://clima.github.io/OceananigansDocumentation/stable/using_gpus/

**Comment by glwagner** [comment] 2021-01-27 18:36
> I don't anticipate the zero Eulerian-mean flow to be a huge issue because my forcing starts up very gradually over the first few hours so I would expect that to act as the spin-up you used in your paper. However, you know much more about this than I do.

Might be best to discuss this elsewhere (eg julia slack), but here's a few thoughts: a zero Eulerian-mean flow is an _excited_ initial condition, not a resting initial condition, which subverts your careful forcing design since zero Eulerian-mean flow shocks the system and excites a huge inertial wave that persists throughout the simulation. I suspect you want to use a "resting" initial condition (eg, the analogue of u=0 in a non-wave-averaged system) --- in which case you should set the Lagrangian-mean flow to 0 (or equivalently leave `u` unset, since this is the default initial condition). We've intentionally written our Craik-Leibovich implementation in terms of the Lagrangian-mean flow with this understanding of wave-averaged physics in mind.

**Comment by sam12396** [comment] 2021-01-29 13:42
Thanks for the support! I have joined the slack channel. To answer @ali-ramadhan's question, pretty much nothing is essential to my setup. This is my first time working in Julia and the current setup is just the first way we figured out how to make it work on a CPU, albeit slowly.

**Comment by ali-ramadhan** [comment] 2021-03-17 03:20
@sam12396 I'm going to close this issue but feel free to reopen if needed! We can continue discussing what should go into a "GPU tips" section in #1478.

**Closed by ali-ramadhan** 2021-03-17 03:20 UTC
