### ISSUE TITLE
Non-trivial bathymetry

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#530] opened 2019-11-12 22:55 UTC
Hi all,
I was wondering if there is plan in near future to support non-trivial bathymetry.
I've seen a vague mention of this in #471 but I don't know what happened after that.
Cheers

**Comment by ali-ramadhan** [comment] 2019-11-13 12:38
Hey @navidcy topography hasn't been a priority for us as we're not looking at any problems where topographic effects are important (yet), although other people have asked about it (cc @hdrake) and we would like to include topography at some point. Some would argue that an ocean model without topography isn't an ocean model...

From discussing this with @glwagner it seems like you could implement topography via an immersed boundary method that accounts for the topography via additional terms in the momentum equation, allowing us to keep using our efficient pressure solver which would be really cool.

@glwagner posted this on Slack a few weeks ago:
> At some point, we should discuss how we plan to implement topography / complex boundaries. Immersed boundary methods (like that used in MITgcm) are probably the right approach. However, MITgcm uses a cut-cell technique that may require modifying the pressure solver. In contrast, a “continuous forcing method” that introduces forcing terms into the mometum / tracer equations to account for the solid boundary could potentially be easier to implement, since the pressure solver would not have to be modified. Here’s a paper that compares two implementations (though their “discrete forcing method” implementation uses ghost cells rather than cut cells as in MITgcm): https://www.sciencedirect.com/science/article/pii/S0009250918306250#b0120

There's also [Tseng & Ferziger (2003)](https://www.sciencedirect.com/science/article/pii/S0021999103004108) who implemented a ghost-cell immersed boundary method (different from the continuous forcing method) in MITgcm with good success.

**Comment by johncmarshall54** [comment] 2019-11-13 12:46
I thought we had decided to leave oceananigans as an LES model. Rather than
develop it further as an all-purpose model. That is what CliMa-O is going
to be.

**Comment by ali-ramadhan** [comment] 2019-11-13 12:57
> I thought we had decided to leave oceananigans as an LES model. Rather than
> develop it further as an all-purpose model. That is what CliMa-O is going
> to be.

Yes that's still the goal. But it seems there are lots of interesting idealized problems where topography plays a big role in the ocean, so you might want to do LES with topography. Not sure if LES model has to be modified to work properly at topographic boundaries.

If it's easy to account for topography via forcing terms in the momentum equation and we don't have to change the pressure solver, then it might make sense to add support for topography as it could make the model useful to more people.

But I don't think we'd be tackling this in the near-term as we have other priorities.

**Comment by glwagner** [comment] 2019-11-13 15:59
While bathymetry is not a priority at the moment, there may be simple, non-invasive methods (from an algorithms standpoint) like the one described in the slack message pasted by @ali-ramadhan for modeling non-rectangular domains. 

Probably the main challenge is not implementing the method (which could take a few days), but verifying and validating the implementation (more likely a few weeks of work at minimum). A collaboration with others who are knowledgeable in Julia and can participate in debugging and validation is probably the best chance for having this feature implemented any time soon, given the time constraints of the main developers.

**Comment by glwagner** [comment] 2019-11-13 17:43
@ali-ramadhan there is no explicit reason why the LES closure itself would fail adjacent to a non-flat boundary. However, typically momentum fluxes associated with a no slip condition have to be parameterized (which you could view as an extension of the LES closure) in wall-bounded LES.

**Comment by ali-ramadhan** [comment] 2021-03-17 02:05
@navidcy I'm going to close this issue since @whitleyv's PR #1368 added an immersed boundary implementation but please reopen if you think the issue is not yet resolved!

**Closed by ali-ramadhan** 2021-03-17 02:05 UTC
Labels: feature 🌟

**Comment by navidcy** [comment] 2021-03-17 02:45
It’s ok to close. We beed an example in the docs!

**Comment by glwagner** [comment] 2021-03-17 14:53
It's experimental so I don't think an example is yet appropriate.
